Plugin fee
cryptoalgebra/Algebra pull request #121
Opened 2024-07-01 15:40 UTC by IliaAzhel

Add plugin fee to beforeSwap and beforeModify(burn)

2024-07-09 15:07 UTC, debych requested changes

2024-07-09 15:07 UTC, debych commented on src/core/contracts/base/ReservesManager.sol
> +    bytes32 slot;
do not sload timestamp if all fee is 0

2024-07-11 16:41 UTC, IliaAzhel commented on src/core/contracts/base/ReservesManager.sol
> +    bytes32 slot;
fixed

2024-07-11 16:46 UTC, IliaAzhel commented on src/core/contracts/base/SwapCalculation.sol
> +    if (pluginFee > overrideFee) revert incorrectPluginFee();
No, If the plugin fee is 0 and the override fee is 0, tx will be reverted.

2024-07-16 12:07 UTC, debych approved these changes

2024-10-11 09:33 UTC, merged